[package]
name = "libant"
version = "0.1.0"
authors = ["geauxvirtual"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.8"
thiserror = "1.0"
crossbeam-channel = "0.5"
log = "0.4"
